spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  issuer: harden.lee@companywe.co.kr
  secretKey: companywe!@#
  accessTokenExpireSeconds: 1800
  refreshTokenExpireSeconds: 2592000

logging:
  level:
    org:
      springframework:
        security: DEBUG
