spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  issuer: harden.lee@companywe.co.kr
  secretKey: companywe!@#



